import { createContext, useContext, useMemo, useState } from "react";

const LanguageContext = createContext(null);

const en = {
  home: "Home",
  chooseRole: "Choose User or Provider",
  chooseRoleHint: "Select your role to continue.",
  userRoleHint: "Book services, track requests, and call providers.",
  providerRoleHint: "Manage bookings, send quotes, and call users.",
  continueAsUser: "Continue as User",
  continueAsProvider: "Continue as Provider",
  userServices: "User Dashboard",
  userDashboard: "User Dashboard",
  userBookings: "My Bookings",
  providerShop: "Provider Dashboard",
  providerDashboard: "Provider Dashboard",
  login: "Login",
  logout: "Logout",
  guest: "Guest",
  language: "Language",
  search: "Search",
  loading: "Loading...",
  createAccount: "Create account",
  myBookings: "My Bookings",
  addService: "Add Service",
  saveShopProfile: "Save Shop Profile",
  incomingRequests: "Booking Requests",
  manageServices: "Manage Services",
  accept: "Accept",
  reject: "Reject",
  complete: "Complete",
  cancel: "Cancel",
  sendQuote: "Send Quote",
  quotePrice: "Quote Price",
  issueLevel: "Issue Level",
  problemText: "Problem Details",
  bookService: "Book Service",
  shopDetails: "Shop Details",
  city: "City",
  address: "Shop Location",
  shopName: "Shop name",
  description: "Description",
  typeOfWork: "Type of work",
  phone: "Phone",
  serviceTitle: "Service title",
  category: "Category",
  searchHint: "Search by cleaner, electrical, plumber, shop name.",
  searchPlaceholder: "Search service/shop/work type",
  loginAsUserToBook: "Login as user to book this service.",
  requestSent: "Request sent to provider.",
  pleaseSelectDate: "Please select date and time.",
  selectedAmount: "Selected amount",
  providerQuote: "Provider quote",
  quoteNote: "Quote note",
  status: "Status",
  scheduled: "Scheduled",
  provider: "Provider",
  work: "Work",
  shop: "Shop",
  minor: "Minor",
  small: "Small",
  major: "Major",
  custom: "Custom",
  customQuote: "Provider quote",
  active: "Active",
  inactive: "Inactive",
  disable: "Disable",
  enable: "Enable",
  editDetails: "Edit Details",
  hideDetails: "Hide Details",
  addNewService: "Add New Service",
  hideServiceForm: "Hide Service Form",
  save: "Save",
  noRequests: "No requests yet",
  customer: "Customer",
  issue: "Issue",
  noData: "N/A",
  alreadyHaveAccount: "Already have account? Login",
  newHereRegister: "New here? Register",
  fullName: "Full name",
  user: "User",
  providerRole: "Provider",
  adminRole: "Admin",
  password: "Password",
  email: "Email",
  pleaseWait: "Please wait...",
  checkingSession: "Checking session...",
  addReview: "Add Review",
  reviewSubmitted: "Review submitted",
  ratingPrompt: "Rating (1-5)",
  commentPrompt: "Comment (optional)",
  profile: "Profile",
  providersAvailable: "Providers Available",
  booked: "Booked",
  accepted: "Accepted",
  rejected: "Rejected",
  pending: "Pending",
  callProvider: "Call Provider",
  callUser: "Call User",
  quickSearchCleaner: "Cleaner",
  quickSearchElectrical: "Electrical",
  quickSearchPlumber: "Plumber",
  quickSearchAcRepair: "AC Repair",
  quickSearchPainting: "Painting",
  status_pending: "Pending",
  status_quote_sent: "Quote Sent",
  status_quote_rejected: "Quote Rejected",
  status_accepted: "Accepted",
  status_completed: "Completed",
  status_cancelled: "Cancelled"
};

const labels = {
  en,
  kn: {
    ...en,
    home: "ಮುಖಪುಟ",
    chooseRole: "ಬಳಕೆದಾರ ಅಥವಾ ಪ್ರೊವೈಡರ್ ಆಯ್ಕೆಮಾಡಿ",
    chooseRoleHint: "ಮುಂದುವರಿಸಲು ನಿಮ್ಮ ಪಾತ್ರವನ್ನು ಆಯ್ಕೆಮಾಡಿ.",
    continueAsUser: "ಬಳಕೆದಾರರಾಗಿ ಮುಂದುವರಿಸಿ",
    continueAsProvider: "ಪ್ರೊವೈಡರ್ ಆಗಿ ಮುಂದುವರಿಸಿ",
    userDashboard: "ಬಳಕೆದಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    userServices: "ಬಳಕೆದಾರ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    providerDashboard: "ಪ್ರೊವೈಡರ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    providerShop: "ಪ್ರೊವೈಡರ್ ಡ್ಯಾಶ್‌ಬೋರ್ಡ್",
    userBookings: "ನನ್ನ ಬುಕ್ಕಿಂಗ್‌ಗಳು",
    myBookings: "ನನ್ನ ಬುಕ್ಕಿಂಗ್‌ಗಳು",
    login: "ಲಾಗಿನ್",
    logout: "ಲಾಗ್‌ಔಟ್",
    guest: "ಅತಿಥಿ",
    language: "ಭಾಷೆ",
    createAccount: "ಖಾತೆ ರಚಿಸಿ",
    city: "ನಗರ",
    address: "ಅಂಗಡಿ ಸ್ಥಳ",
    shopName: "ಅಂಗಡಿ ಹೆಸರು",
    description: "ವಿವರಣೆ",
    typeOfWork: "ಕೆಲಸದ ಪ್ರಕಾರ",
    phone: "ಫೋನ್",
    issueLevel: "ಸಮಸ್ಯೆ ಮಟ್ಟ",
    problemText: "ಸಮಸ್ಯೆ ವಿವರ",
    bookService: "ಸೇವೆ ಬುಕ್ ಮಾಡಿ",
    status: "ಸ್ಥಿತಿ",
    scheduled: "ನಿಗದಿತ ಸಮಯ",
    provider: "ಪ್ರೊವೈಡರ್",
    work: "ಕೆಲಸ",
    minor: "ಸಣ್ಣ",
    small: "ಮಧ್ಯಮ",
    major: "ದೊಡ್ಡ",
    custom: "ಕಸ್ಟಮ್",
    active: "ಸಕ್ರಿಯ",
    inactive: "ನಿಷ್ಕ್ರಿಯ",
    save: "ಉಳಿಸಿ",
    user: "ಬಳಕೆದಾರ",
    providerRole: "ಪ್ರೊವೈಡರ್",
    adminRole: "ನಿರ್ವಾಹಕ",
    password: "ಪಾಸ್ವರ್ಡ್",
    email: "ಇಮೇಲ್",
    checkingSession: "ಸೆಷನ್ ಪರಿಶೀಲಿಸಲಾಗುತ್ತಿದೆ...",
    profile: "ಪ್ರೊಫೈಲ್",
    providersAvailable: "ಲಭ್ಯವಿರುವ ಪ್ರೊವೈಡರ್‌ಗಳು",
    booked: "ಬುಕ್ ಮಾಡಲಾಗಿದೆ",
    accepted: "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    rejected: "ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
    pending: "ಬಾಕಿ",
    callProvider: "ಪ್ರೊವೈಡರ್‌ಗೆ ಕರೆ",
    callUser: "ಬಳಕೆದಾರರಿಗೆ ಕರೆ",
    quickSearchCleaner: "ಕ್ಲೀನರ್",
    quickSearchElectrical: "ಎಲೆಕ್ಟ್ರಿಕಲ್",
    quickSearchPlumber: "ಪ್ಲಂಬರ್",
    quickSearchAcRepair: "ಎಸಿ ರಿಪೇರ್",
    quickSearchPainting: "ಪೇಂಟಿಂಗ್",
    status_pending: "ಬಾಕಿ",
    status_quote_sent: "ಕೋಟ್ ಕಳುಹಿಸಲಾಗಿದೆ",
    status_quote_rejected: "ಕೋಟ್ ತಿರಸ್ಕರಿಸಲಾಗಿದೆ",
    status_accepted: "ಸ್ವೀಕರಿಸಲಾಗಿದೆ",
    status_completed: "ಪೂರ್ಣಗೊಂಡಿದೆ",
    status_cancelled: "ರದ್ದಾಗಿದೆ"
  },
  hi: {
    ...en,
    home: "होम",
    chooseRole: "यूज़र या प्रोवाइडर चुनें",
    chooseRoleHint: "आगे बढ़ने के लिए अपनी भूमिका चुनें।",
    userRoleHint: "सेवा बुक करें, रिक्वेस्ट ट्रैक करें और प्रोवाइडर को कॉल करें।",
    providerRoleHint: "बुकिंग मैनेज करें, कोट भेजें और यूज़र को कॉल करें।",
    continueAsUser: "यूज़र के रूप में जारी रखें",
    continueAsProvider: "प्रोवाइडर के रूप में जारी रखें",
    userDashboard: "यूज़र डैशबोर्ड",
    userServices: "यूज़र डैशबोर्ड",
    providerDashboard: "प्रोवाइडर डैशबोर्ड",
    providerShop: "प्रोवाइडर डैशबोर्ड",
    userBookings: "मेरी बुकिंग",
    myBookings: "मेरी बुकिंग",
    login: "लॉगिन",
    logout: "लॉगआउट",
    guest: "अतिथि",
    language: "भाषा",
    createAccount: "खाता बनाएं",
    city: "शहर",
    address: "दुकान का पता",
    shopName: "दुकान का नाम",
    description: "विवरण",
    typeOfWork: "काम का प्रकार",
    phone: "फ़ोन",
    issueLevel: "समस्या स्तर",
    problemText: "समस्या विवरण",
    bookService: "सेवा बुक करें",
    status: "स्थिति",
    scheduled: "निर्धारित समय",
    provider: "प्रोवाइडर",
    work: "काम",
    minor: "छोटा",
    small: "मध्यम",
    major: "बड़ा",
    custom: "कस्टम",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    save: "सेव करें",
    user: "यूज़र",
    providerRole: "प्रोवाइडर",
    adminRole: "एडमिन",
    password: "पासवर्ड",
    email: "ईमेल",
    checkingSession: "सेशन जांचा जा रहा है...",
    profile: "प्रोफ़ाइल",
    providersAvailable: "उपलब्ध प्रोवाइडर",
    booked: "बुक किया गया",
    accepted: "स्वीकार",
    rejected: "अस्वीकार",
    pending: "लंबित",
    callProvider: "प्रोवाइडर को कॉल करें",
    callUser: "यूज़र को कॉल करें",
    quickSearchCleaner: "क्लीनर",
    quickSearchElectrical: "इलेक्ट्रिकल",
    quickSearchPlumber: "प्लंबर",
    quickSearchAcRepair: "एसी रिपेयर",
    quickSearchPainting: "पेंटिंग",
    status_pending: "लंबित",
    status_quote_sent: "कोट भेजा गया",
    status_quote_rejected: "कोट अस्वीकृत",
    status_accepted: "स्वीकृत",
    status_completed: "पूर्ण",
    status_cancelled: "रद्द"
  },
  ta: {
    ...en,
    home: "முகப்பு",
    chooseRole: "பயனர் அல்லது வழங்குநரை தேர்வு செய்க",
    chooseRoleHint: "தொடர உங்கள் பங்கை தேர்வு செய்யவும்.",
    continueAsUser: "பயனராக தொடரவும்",
    continueAsProvider: "வழங்குநராக தொடரவும்",
    userDashboard: "பயனர் டாஷ்போர்டு",
    userServices: "பயனர் டாஷ்போர்டு",
    providerDashboard: "வழங்குநர் டாஷ்போர்டு",
    providerShop: "வழங்குநர் டாஷ்போர்டு",
    userBookings: "என் பதிவுகள்",
    myBookings: "என் பதிவுகள்",
    login: "உள்நுழை",
    logout: "வெளியேறு",
    guest: "விருந்தினர்",
    language: "மொழி",
    createAccount: "கணக்கு உருவாக்கு",
    city: "நகரம்",
    address: "கடை முகவரி",
    shopName: "கடை பெயர்",
    description: "விவரம்",
    typeOfWork: "வேலை வகை",
    phone: "தொலைபேசி",
    issueLevel: "பிரச்சனை நிலை",
    problemText: "பிரச்சனை விவரம்",
    bookService: "சேவையை பதிவு செய்",
    status: "நிலை",
    scheduled: "திட்டமிட்ட நேரம்",
    provider: "வழங்குநர்",
    work: "வேலை",
    minor: "சிறியது",
    small: "நடுத்தரம்",
    major: "பெரியது",
    custom: "தனிப்பயன்",
    active: "செயலில்",
    inactive: "செயலற்றது",
    save: "சேமி",
    user: "பயனர்",
    providerRole: "வழங்குநர்",
    adminRole: "நிர்வாகி",
    password: "கடவுச்சொல்",
    email: "மின்னஞ்சல்",
    checkingSession: "அமர்வு சரிபார்க்கப்படுகிறது...",
    profile: "சுயவிவரம்",
    providersAvailable: "கிடைக்கும் வழங்குநர்கள்",
    booked: "பதிவு செய்யப்பட்டது",
    accepted: "ஏற்கப்பட்டது",
    rejected: "நிராகரிக்கப்பட்டது",
    pending: "நிலுவையில்",
    callProvider: "வழங்குநருக்கு அழைக்கவும்",
    callUser: "பயனருக்கு அழைக்கவும்",
    quickSearchCleaner: "தூய்மை பணியாளர்",
    quickSearchElectrical: "மின்சாரம்",
    quickSearchPlumber: "குழாய் நிபுணர்",
    quickSearchAcRepair: "ஏசி பழுது",
    quickSearchPainting: "வண்ணப்பணி",
    status_pending: "நிலுவையில்",
    status_quote_sent: "விலை அனுப்பப்பட்டது",
    status_quote_rejected: "விலை நிராகரிக்கப்பட்டது",
    status_accepted: "ஏற்கப்பட்டது",
    status_completed: "முடிந்தது",
    status_cancelled: "ரத்து செய்யப்பட்டது"
  },
  te: {
    ...en,
    home: "హోమ్",
    chooseRole: "యూజర్ లేదా ప్రొవైడర్ ఎంచుకోండి",
    chooseRoleHint: "కొనసాగడానికి మీ పాత్రను ఎంచుకోండి.",
    continueAsUser: "యూజర్‌గా కొనసాగండి",
    continueAsProvider: "ప్రొవైడర్‌గా కొనసాగండి",
    userDashboard: "యూజర్ డాష్‌బోర్డ్",
    userServices: "యూజర్ డాష్‌బోర్డ్",
    providerDashboard: "ప్రొవైడర్ డాష్‌బోర్డ్",
    providerShop: "ప్రొవైడర్ డాష్‌బోర్డ్",
    userBookings: "నా బుకింగ్స్",
    myBookings: "నా బుకింగ్స్",
    login: "లాగిన్",
    logout: "లాగౌట్",
    guest: "అతిథి",
    language: "భాష",
    createAccount: "ఖాతా సృష్టించండి",
    city: "నగరం",
    address: "షాప్ చిరునామా",
    shopName: "షాప్ పేరు",
    description: "వివరణ",
    typeOfWork: "పని రకం",
    phone: "ఫోన్",
    issueLevel: "సమస్య స్థాయి",
    problemText: "సమస్య వివరాలు",
    bookService: "సేవ బుక్ చేయండి",
    status: "స్థితి",
    scheduled: "షెడ్యూల్ చేసిన సమయం",
    provider: "ప్రొవైడర్",
    work: "పని",
    minor: "చిన్నది",
    small: "మధ్యస్థం",
    major: "పెద్దది",
    custom: "కస్టమ్",
    active: "యాక్టివ్",
    inactive: "ఇనాక్టివ్",
    save: "సేవ్",
    user: "యూజర్",
    providerRole: "ప్రొవైడర్",
    adminRole: "అడ్మిన్",
    password: "పాస్‌వర్డ్",
    email: "ఈమెయిల్",
    checkingSession: "సెషన్ తనిఖీ చేస్తోంది...",
    profile: "ప్రొఫైల్",
    providersAvailable: "లభ్యమైన ప్రొవైడర్లు",
    booked: "బుక్ చేయబడింది",
    accepted: "ఆమోదించబడింది",
    rejected: "తిరస్కరించబడింది",
    pending: "పెండింగ్",
    callProvider: "ప్రొవైడర్‌కు కాల్ చేయండి",
    callUser: "యూజర్‌కు కాల్ చేయండి",
    quickSearchCleaner: "క్లీనర్",
    quickSearchElectrical: "ఎలక్ట్రికల్",
    quickSearchPlumber: "ప్లంబర్",
    quickSearchAcRepair: "ఏసీ రిపేర్",
    quickSearchPainting: "పెయింటింగ్",
    status_pending: "పెండింగ్",
    status_quote_sent: "కోట్ పంపబడింది",
    status_quote_rejected: "కోట్ తిరస్కరించబడింది",
    status_accepted: "ఆమోదించబడింది",
    status_completed: "పూర్తయింది",
    status_cancelled: "రద్దు చేయబడింది"
  },
  mr: {
    ...en,
    home: "मुख्यपृष्ठ",
    chooseRole: "यूजर किंवा प्रोव्हायडर निवडा",
    chooseRoleHint: "पुढे जाण्यासाठी तुमची भूमिका निवडा.",
    continueAsUser: "यूजर म्हणून पुढे जा",
    continueAsProvider: "प्रोव्हायडर म्हणून पुढे जा",
    userDashboard: "यूजर डॅशबोर्ड",
    userServices: "यूजर डॅशबोर्ड",
    providerDashboard: "प्रोव्हायडर डॅशबोर्ड",
    providerShop: "प्रोव्हायडर डॅशबोर्ड",
    userBookings: "माझी बुकिंग",
    myBookings: "माझी बुकिंग",
    login: "लॉगिन",
    logout: "लॉगआउट",
    guest: "अतिथी",
    language: "भाषा",
    createAccount: "खाते तयार करा",
    city: "शहर",
    address: "दुकान पत्ता",
    shopName: "दुकान नाव",
    description: "वर्णन",
    typeOfWork: "कामाचा प्रकार",
    phone: "फोन",
    issueLevel: "समस्या स्तर",
    problemText: "समस्या तपशील",
    bookService: "सेवा बुक करा",
    status: "स्थिती",
    scheduled: "नियोजित वेळ",
    provider: "प्रोव्हायडर",
    work: "काम",
    minor: "लहान",
    small: "मध्यम",
    major: "मोठे",
    custom: "कस्टम",
    active: "सक्रिय",
    inactive: "निष्क्रिय",
    save: "सेव्ह",
    user: "यूजर",
    providerRole: "प्रोव्हायडर",
    adminRole: "अ‍ॅडमिन",
    password: "पासवर्ड",
    email: "ईमेल",
    checkingSession: "सेशन तपासले जात आहे...",
    profile: "प्रोफाइल",
    providersAvailable: "उपलब्ध प्रोव्हायडर्स",
    booked: "बुक झालेले",
    accepted: "स्वीकारलेले",
    rejected: "नाकारण्यात आलेले",
    pending: "प्रलंबित",
    callProvider: "प्रोव्हायडरला कॉल करा",
    callUser: "यूजरला कॉल करा",
    quickSearchCleaner: "क्लिनर",
    quickSearchElectrical: "इलेक्ट्रिकल",
    quickSearchPlumber: "प्लंबर",
    quickSearchAcRepair: "एसी दुरुस्ती",
    quickSearchPainting: "पेंटिंग",
    status_pending: "प्रलंबित",
    status_quote_sent: "कोट पाठवला",
    status_quote_rejected: "कोट नाकारला",
    status_accepted: "स्वीकारले",
    status_completed: "पूर्ण झाले",
    status_cancelled: "रद्द"
  }
};

export const languageOptions = [
  { code: "en", label: "English" },
  { code: "kn", label: "ಕನ್ನಡ" },
  { code: "hi", label: "हिन्दी" },
  { code: "ta", label: "தமிழ்" },
  { code: "te", label: "తెలుగు" },
  { code: "mr", label: "मराठी" }
];

function statusFallback(key) {
  if (!key.startsWith("status_")) return null;

  return key
    .replace("status_", "")
    .split("_")
    .filter(Boolean)
    .map((part) => part.charAt(0).toUpperCase() + part.slice(1))
    .join(" ");
}

export function LanguageProvider({ children }) {
  const [language, setLanguageState] = useState(localStorage.getItem("neednest_lang") || "en");

  const value = useMemo(
    () => ({
      language,
      setLanguage(code) {
        localStorage.setItem("neednest_lang", code);
        setLanguageState(code);
      },
      t(key) {
        return labels[language]?.[key] || en[key] || statusFallback(key) || key;
      }
    }),
    [language]
  );

  return <LanguageContext.Provider value={value}>{children}</LanguageContext.Provider>;
}

export function useLanguage() {
  const ctx = useContext(LanguageContext);
  if (!ctx) throw new Error("useLanguage must be used inside LanguageProvider");
  return ctx;
}
